services:
  wordpress:
    build: ./
    restart: always
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: smailydev1
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MAILHOG_HOST', 'mailhog' );
    volumes:
    - wordpress:/var/www/html
    - ./:/var/www/html/wp-content/plugins/smaily

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: smailydev1
    volumes:
    - db:/var/lib/mysql
    ulimits:
      nofile:
        soft: 65563
        hard: 65563

  phpmyadmin:
    depends_on:
    - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - '8888:80'
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: smailydev1
      MYSQL_ROOT_PASSWORD: smailydev1

  mailhog:
    image: mailhog/mailhog
    ports:
    - 8025:8025

volumes:
  wordpress:
  db:
