name: Lint and test the codebase

on: pull_request

jobs:
  lint_and_test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache PHP packages
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
          ${{ runner.os }}-

    - name: Cache Node modules
      uses: actions/cache@v3
      with:
        path: blocks/*/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('blocks/*/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - name: Set up PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        tools: composer

    - name: Set up Node environment
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install PHP dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Install Node dependencies
      run: composer run install-block-modules

    - name: Lint
      run: composer run lint

    - name: Test
      run: composer run test
